// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _4LumenBackEnd.Models;

#nullable disable

namespace _4LumenBackEnd.Migrations
{
    [DbContext(typeof(XmlDetailsContext))]
    [Migration("20241122034406_First Migration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_4LumenBackEnd.Models.XMLDetails", b =>
                {
                    b.Property<int>("XmlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("XmlId"));

                    b.Property<DateTime>("DataXml")
                        .HasColumnType("date");

                    b.Property<string>("XmlContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("XmlId");

                    b.ToTable("XMLDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
